"use client";

import Link from "next/link";
import { products, formatPrice } from "@/lib/catalog";
import { removeProduct, setProductQuantity, useCart } from "@/lib/cart";
import { StoreFooter, StoreHeader } from "@/components/storefront";

export default function CartPage() {
  const { lines } = useCart();
  const rows = lines.map((line) => ({ line, product: products.find((product) => product.slug === line.slug) })).filter((item) => item.product);
  const subtotal = rows.reduce((sum, row) => sum + row.product!.price * row.line.quantity, 0);
  return <div className="min-h-screen bg-[#FAF7F0] text-[#183B2B]"><StoreHeader /><main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 md:py-12"><Link href="/" className="text-sm font-semibold text-[#287A4B] hover:underline">← Continue shopping</Link><div className="mt-5 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#287A4B]">Your selection</p><h1 className="mt-1 text-4xl" style={{ fontFamily: "'DM Serif Display', Georgia, serif" }}>Your basket</h1></div><span className="text-sm text-[#748076]">{lines.reduce((sum, line) => sum + line.quantity, 0)} items</span></div>
    {rows.length === 0 ? <div className="mt-8 rounded-2xl border border-dashed border-[#c9d4c9] bg-white/70 px-6 py-16 text-center"><span className="text-4xl" aria-hidden="true">🧺</span><h2 className="mt-4 text-xl font-semibold">Your basket is taking a breather</h2><p className="mt-2 text-sm text-[#748076]">Find something fresh for your table in our sample market.</p><Link href="/" className="mt-6 inline-flex rounded-full bg-[#287A4B] px-6 py-3 text-sm font-semibold text-white hover:bg-[#1e633b]">Continue shopping</Link></div> : <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_340px] lg:items-start"><section className="space-y-3" aria-label="Basket items">{rows.map(({ line, product }) => product && <article key={line.slug} className="flex gap-3 rounded-2xl border border-[#e9e3d8] bg-white p-3 sm:gap-5 sm:p-4"><Link href={`/product/${product.slug}`} className="h-24 w-24 shrink-0 overflow-hidden rounded-xl bg-[#E5F2E8] sm:h-28 sm:w-28"><img src={product.image} alt={product.name} className="h-full w-full object-cover" /></Link><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><div className="min-w-0"><Link href={`/product/${product.slug}`} className="font-semibold hover:text-[#287A4B]">{product.name}</Link><p className="mt-1 text-xs text-[#7b847c]">{product.unit} · {formatPrice(product.price)} each</p></div><span className="whitespace-nowrap text-sm font-bold">{formatPrice(product.price * line.quantity)}</span></div><div className="mt-4 flex items-center justify-between"><div className="inline-flex items-center rounded-full border border-[#ded9ce]" aria-label={`Quantity of ${product.name}`}><button aria-label={`Decrease ${product.name} quantity`} onClick={() => setProductQuantity(line.slug, line.quantity - 1)} className="h-8 w-9 rounded-l-full text-lg hover:bg-[#E5F2E8]">−</button><span className="min-w-8 text-center text-sm font-semibold">{line.quantity}</span><button aria-label={`Increase ${product.name} quantity`} onClick={() => setProductQuantity(line.slug, line.quantity + 1)} className="h-8 w-9 rounded-r-full text-lg hover:bg-[#E5F2E8]">+</button></div><button onClick={() => removeProduct(line.slug)} className="text-xs font-semibold text-[#a35742] underline underline-offset-4 hover:text-[#7e3424]">Remove</button></div></div></article>)}</section>
      <aside className="rounded-2xl border border-[#e9e3d8] bg-white p-5 sm:p-6"><h2 className="text-lg font-semibold">Order summary</h2><div className="mt-5 flex justify-between border-b border-[#eee9df] pb-4 text-sm"><span className="text-[#68766c]">Subtotal</span><span className="font-semibold">{formatPrice(subtotal)}</span></div><p className="mt-4 text-xs leading-5 text-[#748076]">Delivery or pickup fees and estimated tax are shown at checkout. All totals are simulated.</p><div className="mt-5 flex justify-between text-base font-bold"><span>Items subtotal</span><span>{formatPrice(subtotal)}</span></div><Link href="/checkout" className="mt-6 flex h-12 items-center justify-center rounded-full bg-[#287A4B] text-sm font-semibold text-white transition hover:bg-[#1e633b] focus:outline-none focus:ring-2 focus:ring-[#287A4B] focus:ring-offset-2">Continue to checkout</Link><p className="mt-3 text-center text-[11px] leading-4 text-[#81877f]">Demo checkout only — no payment or real order.</p></aside>
    </div>}</main><StoreFooter /></div>;
}
