"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import ShopNav from "@/components/shop-nav";
import { getCart, products, saveCart, type CartLine } from "@/lib/grocery";

export default function CartPage() {
  const [cart, setCartState] = useState<CartLine[]>([]);
  const [ready, setReady] = useState(false);
  useEffect(() => { setCartState(getCart()); setReady(true); }, []);
  const subtotal = useMemo(() => cart.reduce((sum, line) => sum + (products.find((item) => item.slug === line.productId)?.price ?? 0) * line.quantity, 0), [cart]);
  function update(next: CartLine[]) { setCartState(next); saveCart(next); }
  return <div className="min-h-screen bg-[#faf7f0] text-[#183b2b]"><ShopNav /><main className="mx-auto max-w-5xl px-5 py-10"><p className="text-sm font-semibold uppercase tracking-wider text-[#287a4b]">Your basket</p><h1 className="mt-2 font-serif text-4xl">Review your groceries</h1><p className="mt-2 text-sm text-[#68766b]">All prices and fulfillment details are simulated for this demo.</p>
    {!ready ? <div className="mt-8 rounded-2xl bg-white p-8 text-[#68766b]">Loading your basket…</div> : cart.length === 0 ? <div className="mt-8 rounded-2xl border border-dashed border-[#c9d4c7] bg-white px-6 py-14 text-center"><h2 className="font-serif text-2xl">Your basket is empty</h2><p className="mt-2 text-sm text-[#68766b]">Find something fresh for your next meal.</p><Link href="/#catalog" className="mt-6 inline-block rounded-full bg-[#287a4b] px-5 py-3 font-semibold text-white hover:bg-[#183b2b]">Continue shopping</Link></div> : <div className="mt-8 grid gap-7 lg:grid-cols-[1fr_320px]">
      <div className="space-y-3">{cart.map((line) => { const product = products.find((item) => item.slug === line.productId); if (!product) return null; return <article key={line.productId} className="flex gap-4 rounded-2xl border border-[#ebe6dc] bg-white p-4"><img src={product.image} alt={product.name} className="h-24 w-24 rounded-xl object-cover" /><div className="min-w-0 flex-1"><Link href={`/product/${product.slug}`} className="font-semibold hover:text-[#287a4b]">{product.name}</Link><p className="mt-1 text-sm text-[#718174]">${product.price.toFixed(2)} · {product.unit}</p><div className="mt-3 flex items-center gap-3"><button type="button" aria-label={`Decrease ${product.name} quantity`} onClick={() => update(line.quantity <= 1 ? cart.filter((item) => item.productId !== line.productId) : cart.map((item) => item.productId === line.productId ? { ...item, quantity: item.quantity - 1 } : item))} className="h-8 w-8 rounded-full border border-[#d8ded6] font-semibold hover:bg-[#e5f2e8]">−</button><span className="min-w-5 text-center text-sm font-semibold">{line.quantity}</span><button type="button" aria-label={`Increase ${product.name} quantity`} onClick={() => update(cart.map((item) => item.productId === line.productId ? { ...item, quantity: item.quantity + 1 } : item))} className="h-8 w-8 rounded-full border border-[#d8ded6] font-semibold hover:bg-[#e5f2e8]">+</button><button type="button" onClick={() => update(cart.filter((item) => item.productId !== line.productId))} className="ml-2 text-sm text-[#a14c3c] hover:underline">Remove</button></div></div><p className="whitespace-nowrap pt-1 font-semibold">${(product.price * line.quantity).toFixed(2)}</p></article>; })}</div>
      <aside className="h-fit rounded-2xl border border-[#ebe6dc] bg-white p-5"><h2 className="font-serif text-xl">Cost summary</h2><div className="mt-5 flex justify-between text-sm"><span>Subtotal</span><span>${subtotal.toFixed(2)}</span></div><p className="mt-2 text-xs leading-5 text-[#718174]">Delivery or pickup fees, if applicable, are shown during demo checkout.</p><div className="my-4 border-t border-[#eee9df]" /><div className="flex justify-between font-semibold"><span>Items subtotal</span><span>${subtotal.toFixed(2)}</span></div><Link href="/checkout" className="mt-5 block rounded-xl bg-[#287a4b] px-5 py-3 text-center font-semibold text-white hover:bg-[#183b2b]">Continue to checkout</Link><Link href="/#catalog" className="mt-4 block text-center text-sm font-semibold text-[#287a4b] hover:underline">Continue shopping</Link><p className="mt-4 text-center text-xs text-[#718174]">Demo only. No payment or real order is made.</p></aside>
    </div>}
  </main></div>;
}
