import Link from "next/link";
import { GroceryHeader } from "@/components/grocery-header";

const questions = [
  { question: "Are these real prices or products?", answer: "No. Products, prices, and availability in this experience are sample data for a demonstration and may not reflect a real store." },
  { question: "Will my order be sent to a grocery store?", answer: "No. Checkout creates a demo order saved in this browser only. It does not contact a retailer or arrange a real delivery or pickup." },
  { question: "Is my payment information collected?", answer: "No payment is collected. This demo does not process payments or request payment details." },
  { question: "Where are my cart and demo order saved?", answer: "Cart and order information is stored locally in your browser. Clearing browser storage or using a different device may remove or hide it." },
  { question: "How do delivery and pickup work here?", answer: "They are simulated choices used to show an example of order totals. No delivery area, time slot, or pickup request is actually confirmed." },
];

export default function HelpPage() {
  return <main className="min-h-screen bg-[#faf7f0] text-[#183b2b]"><GroceryHeader /><div className="mx-auto max-w-4xl px-4 py-10 sm:px-6 sm:py-14"><p className="text-sm font-bold uppercase tracking-[0.14em] text-[#287a4b]">Here to help</p><h1 className="mt-2 font-serif text-5xl">Good to know.</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-[#496454]">AAA Grocery is a shopping demo designed to make a sample grocery order easy to explore. Here’s what that means for you.</p><section className="mt-8 rounded-2xl border border-[#d9e8dc] bg-[#e5f2e8] p-6 sm:p-7"><h2 className="font-serif text-2xl">Demo limitations</h2><p className="mt-3 leading-7 text-[#496454]">This site does not represent a real retailer. Catalog items, inventory, pricing, fees, delivery, and pickup are simulated. Placing an order only saves a confirmation on this device. No real order or payment is submitted.</p></section><section id="account" className="mt-10"><h2 className="font-serif text-3xl">Frequently asked questions</h2><div className="mt-5 space-y-3">{questions.map((item) => <details key={item.question} className="group rounded-xl border border-[#e8e3d9] bg-white p-5"><summary className="cursor-pointer list-none font-semibold marker:hidden focus:outline-none focus-visible:ring-2 focus-visible:ring-[#287a4b]">{item.question}<span className="float-right text-[#287a4b] transition group-open:rotate-45" aria-hidden="true">＋</span></summary><p className="mt-3 max-w-3xl text-sm leading-6 text-[#66766a]">{item.answer}</p></details>)}</div></section><section className="mt-10 rounded-2xl border border-[#e8e3d9] bg-white p-6"><h2 className="font-serif text-2xl">Contact</h2><p className="mt-2 text-sm leading-6 text-[#66766a]">Need help navigating the demo? This sample experience has no live customer support channel, but you can browse the catalog or review your locally saved demo cart.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/" className="rounded-full bg-[#287a4b] px-5 py-2.5 text-sm font-semibold text-white hover:bg-[#1f633c]">Shop groceries</Link><Link href="/cart" className="rounded-full border border-[#cdd8cc] px-5 py-2.5 text-sm font-semibold text-[#183b2b] hover:bg-[#f5f7f3]">View cart</Link></div></section></div></main>;
}
