"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { GroceryHeader } from "@/components/grocery-header";
import { formatPrice, getOrderById, getProductById } from "@/lib/grocery";

export default function OrderDetailsPage() {
  const { id } = useParams<{ id: string }>();
  const order = getOrderById(id);

  return <main className="min-h-screen bg-[#faf7f0] text-[#183b2b]"><GroceryHeader /><div className="mx-auto max-w-3xl px-4 py-10 sm:px-6"><Link href="/" className="text-sm font-semibold text-[#287a4b] hover:underline">← Continue shopping</Link>{!order ? <section className="mt-7 rounded-2xl border border-[#e6e1d7] bg-white p-8 text-center"><h1 className="font-serif text-3xl">Demo order not found</h1><p className="mt-3 text-sm leading-6 text-[#66766a]">Order details are saved on this device only. The order may have been cleared or created in another browser.</p><Link href="/" className="mt-6 inline-flex rounded-full bg-[#287a4b] px-6 py-3 text-sm font-semibold text-white">Shop groceries</Link></section> : <><section className="mt-7 rounded-3xl bg-[#e5f2e8] p-7 sm:p-10"><p className="text-sm font-bold uppercase tracking-[0.14em] text-[#287a4b]">Demo order confirmed</p><h1 className="mt-2 font-serif text-4xl">Thanks for trying AAA Grocery.</h1><p className="mt-4 max-w-xl leading-7 text-[#496454]">This confirmation is saved locally as a demo. No payment, retailer, delivery, or pickup request was made.</p><p className="mt-5 text-sm font-semibold">Order reference: <span className="font-mono">{order.id}</span></p><p className="mt-1 text-sm text-[#66766a]">Placed {new Date(order.placedAt).toLocaleString()}</p></section><section className="mt-6 rounded-2xl border border-[#e8e3d9] bg-white p-6"><h2 className="font-serif text-2xl">Order details</h2><p className="mt-2 text-sm text-[#66766a]">{order.fulfillment === "delivery" ? "Demo delivery" : "Demo pickup"} · Simulated fulfillment</p><div className="mt-5 divide-y divide-[#eee9e0]">{order.items.map((line) => { const product = getProductById(line.productId); if (!product) return null; return <div key={line.productId} className="flex items-center justify-between gap-4 py-4"><div><p className="font-semibold">{product.name}</p><p className="mt-1 text-sm text-[#66766a]">{line.quantity} × {formatPrice(product.price)}</p></div><p className="font-semibold">{formatPrice(product.price * line.quantity)}</p></div>; })}</div><div className="mt-4 space-y-2 border-t border-[#eee9e0] pt-4 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{formatPrice(order.subtotal)}</span></div><div className="flex justify-between"><span>Simulated fulfillment fee</span><span>{formatPrice(order.fee)}</span></div><div className="flex justify-between pt-2 text-base font-bold"><span>Total</span><span>{formatPrice(order.total)}</span></div></div></section><p className="mt-6 text-center text-sm text-[#66766a]">Questions? Visit our <Link href="/help" className="font-semibold text-[#287a4b] underline">Help page</Link>.</p></>}</div></main>;
}
