"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import GroceryNav from "@/components/grocery-nav";
import { categories, money, products } from "@/lib/grocery-data";

export default function Catalog() {
  const [category, setCategory] = useState("All");
  const [query, setQuery] = useState("");
  const visible = useMemo(() => products.filter((product) => (category === "All" || product.category === category) && product.name.toLowerCase().includes(query.trim().toLowerCase())), [category, query]);
  return <main className="min-h-screen bg-[#faf7f0] text-[#183b2b]"><GroceryNav /><section className="mx-auto grid max-w-7xl gap-8 px-5 py-9 md:grid-cols-[1.05fr_.95fr] md:items-center md:py-14"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-[#287a4b]">Your neighborhood, in season</p><h1 className="mt-3 max-w-xl font-serif text-5xl font-bold leading-tight md:text-6xl">Good food, closer to home.</h1><p className="mt-5 max-w-lg text-lg leading-8 text-[#617367]">Find everyday favorites and fresh local picks in one easy basket. Browse our sample grocery collection.</p><a href="#catalog" className="mt-7 inline-flex rounded-full bg-[#287a4b] px-6 py-3 font-semibold text-white transition hover:bg-[#1e633b]">Shop groceries</a><p className="mt-4 text-xs text-[#617367]">A demo experience: no real orders or payments.</p></div><div className="relative overflow-hidden rounded-[2rem] bg-[#e5f2e8] p-3"><div className="absolute -right-8 -top-8 h-48 w-48 rounded-full border border-[#287a4b]/20"/><img className="h-72 w-full rounded-[1.5rem] object-cover md:h-[370px]" src="https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1400&q=90" alt="Colorful fresh produce at a neighborhood market"/><div className="absolute bottom-7 left-7 rounded-2xl bg-white/95 px-4 py-3 shadow"><p className="font-serif text-lg font-bold">Fresh finds, every day</p><p className="text-sm text-[#617367]">Curated for your neighborhood</p></div></div></section>
    <section id="catalog" className="mx-auto max-w-7xl scroll-mt-4 px-5 pb-16"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-wider text-[#287a4b]">The sample shop</p><h2 className="mt-1 font-serif text-3xl font-bold">What sounds good?</h2></div><label className="w-full md:max-w-sm"><span className="sr-only">Search products</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search groceries..." className="h-12 w-full rounded-xl border border-[#ded8cd] bg-white px-4 outline-none transition placeholder:text-[#89958c] focus:border-[#287a4b] focus:ring-2 focus:ring-[#287a4b]/15" /></label></div>
      <div className="mt-6 flex gap-2 overflow-x-auto pb-2" aria-label="Product categories"><button onClick={() => setCategory("All")} className={`shrink-0 rounded-full px-4 py-2 text-sm font-semibold ${category === "All" ? "bg-[#287a4b] text-white" : "bg-white text-[#183b2b] hover:bg-[#e5f2e8]"}`}>All</button>{categories.map((name) => <button key={name} onClick={() => setCategory(name)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-semibold transition ${category === name ? "bg-[#287a4b] text-white" : "bg-white text-[#183b2b] hover:bg-[#e5f2e8]"}`}>{name}</button>)}</div>
      {visible.length ? <div className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">{visible.map((product) => <Link href={`/product/${product.slug}`} key={product.slug} className="group overflow-hidden rounded-2xl border border-[#e9e2d7] bg-white transition hover:-translate-y-1 hover:shadow-lg focus:outline-none focus:ring-2 focus:ring-[#287a4b]"><div className="overflow-hidden bg-[#e5f2e8]"><img src={product.image} alt={product.name} className="h-40 w-full object-cover transition duration-300 group-hover:scale-105 sm:h-48" /></div><div className="p-4"><p className="text-xs font-semibold text-[#287a4b]">{product.category}</p><h3 className="mt-1 min-h-10 font-semibold leading-5">{product.name}</h3><div className="mt-3 flex items-baseline justify-between gap-2"><span className="font-bold text-[#183b2b]">{money(product.price)}</span><span className="text-xs text-[#617367]">{product.unit}</span></div><span className="mt-3 block text-sm font-semibold text-[#287a4b]">View product →</span></div></Link>)}</div> : <div className="mt-8 rounded-2xl border border-dashed border-[#cfc8bc] bg-white p-10 text-center"><p className="font-serif text-2xl font-bold">No groceries found</p><p className="mt-2 text-[#617367]">{query ? `We couldn't find anything for “${query}”. Try another search or clear it.` : "There are no products in this category yet."}</p><button onClick={() => { setQuery(""); setCategory("All"); }} className="mt-5 rounded-full bg-[#287a4b] px-5 py-2.5 font-semibold text-white">Show all products</button></div>}</section></main>;
}
