'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { DemoOrder, ORDERS_KEY, findProduct } from '@/lib/grocery';
import { readLocal } from '@/lib/persist';
import { addToCart, PageShell } from '@/components/shop';

export default function OrderPage() {
  const params = useParams<{ orderId: string }>();
  const [order, setOrder] = useState<DemoOrder | null>(null);
  useEffect(() => setOrder(readLocal<DemoOrder[]>(ORDERS_KEY, []).find((item) => item.id === params.orderId) ?? null), [params.orderId]);
  if (!order) return <PageShell><main className='mx-auto max-w-3xl px-4 py-16 text-center'><div className='text-5xl'>🧺</div><h1 className='mt-4 font-serif text-4xl'>Demo order not found</h1><p className='mt-3 text-[#68736b]'>This confirmation may have been cleared from this browser.</p><Link href='/account' className='mt-6 inline-block rounded-full bg-[#287A4B] px-6 py-3 font-semibold text-white'>View order history</Link></main></PageShell>;
  return <PageShell><main className='mx-auto max-w-3xl px-4 py-10 sm:px-6'><div className='rounded-3xl border border-[#d5e7d9] bg-[#E5F2E8] p-7 sm:p-10'><p className='font-bold uppercase tracking-widest text-[#287A4B]'>Demo order confirmed</p><h1 className='mt-3 font-serif text-4xl'>Thanks, {order.name}!</h1><p className='mt-3 leading-7'>Your demo order is saved on this device. No retailer has received it, and no payment has been taken.</p><p className='mt-4 text-sm text-[#526358]'>Order reference: <strong>{order.id}</strong></p></div><section className='mt-7 rounded-2xl border border-[#e8e1d5] bg-white p-6'><h2 className='font-serif text-2xl'>Order details</h2><p className='mt-2 text-sm text-[#68736b]'>{new Date(order.createdAt).toLocaleString()} · {order.fulfillment === 'delivery' ? 'Demo delivery' : 'Demo pickup'}</p><div className='mt-5 divide-y divide-[#eee9df]'>{order.items.map((line) => { const product = findProduct(line.slug); return product ? <div key={line.slug} className='flex justify-between gap-4 py-3'><span>{product.name} × {line.quantity}</span><span>${(product.price * line.quantity).toFixed(2)}</span></div> : null; })}</div><div className='mt-4 space-y-2 border-t border-[#e8e1d5] pt-4 text-sm'><div className='flex justify-between'><span>Subtotal</span><span>${order.subtotal.toFixed(2)}</span></div><div className='flex justify-between'><span>{order.fulfillment === 'delivery' ? 'Demo delivery fee' : 'Pickup fee'}</span><span>${order.fee.toFixed(2)}</span></div><div className='flex justify-between'><span>Estimated tax</span><span>${order.tax.toFixed(2)}</span></div><div className='flex justify-between pt-2 text-base font-bold'><span>Estimated total</span><span>${order.total.toFixed(2)}</span></div></div><div className='mt-6 flex flex-wrap gap-3'><Link href='/account' className='rounded-full border border-[#287A4B] px-5 py-2.5 font-semibold text-[#287A4B]'>Order history</Link><Link href='/help' className='rounded-full border border-[#d9d4ca] px-5 py-2.5 font-semibold'>Help and FAQs</Link><Link href='/' className='rounded-full bg-[#287A4B] px-5 py-2.5 font-semibold text-white'>Continue shopping</Link></div></section></main></PageShell>;
}
